---
- name: This sets up an httpd webserver
  host: web
  vars: 
    name: "--amish doamdiya in playbook--"
    message: "Hello everyone"
    package: httpd
  
  tasks:
  - name: Install the httpd apps
    yum: name={{ package }} state=present
    when: ansible_os_family == "RedHat"
  - name: Install the httpd apps
    apt: name={{ package }} state=present
    when: ansible_os_family == "Debian"
  - name: start the httpd service
    service: name={{ packge }} state=started
  - name: create a empty file 
    file: dest=/opt/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="index.html"
  - debug:
      msg: My Name is {{ name }} and my message is {{ message }}
... 